#!/usr/bin/env python3
# preset4_1
# preset#4 high_right
# preset for pan tilt module for use in motioneye

# 2017 03 15 SeJ init

### imports
import pantilthat

# pantilt settings
pan = -45
tilt = 0

# offsets
poff = 20
toff = 30


pantilthat.pan(pan + poff)
pantilthat.tilt(tilt + toff)

