#!/usr/bin/env python3
# preset7_1
# preset#7 low_mid_right
# preset for pan tilt module for use in motioneye

# 2017 03 15 SeJ init

### imports
import pantilthat

# pantilt settings
pan = -20
tilt = 30

# offsets
poff = 20
toff = 30


pantilthat.pan(pan + poff)
pantilthat.tilt(tilt + toff)

