#!/usr/bin/env python3
# preset1_1
# preset#1 high_left
# preset for pan tilt module for use in motioneye

# 2017 03 15 SeJ init

### imports
import pantilthat

# pantilt settings
pan = 45
tilt = 7

# offsets
poff = 15
toff = 5


pantilthat.pan(pan + poff)
pantilthat.tilt(tilt + toff)

