#!/usr/bin/env python3
# preset2_1
# preset#2 high_mid_left
# preset for pan tilt module for use in motioneye

# 2017 03 15 SeJ init

### imports
import pantilthat

# pantilt settings
pan = 20
tilt = 7

# offsets
poff = 15
toff = 5


pantilthat.pan(pan + poff)
pantilthat.tilt(tilt + toff)

