#!/usr/bin/env python3
# preset2_1
# preset#2 high_mid_left
# preset for pan tilt module for use in motioneye

# 2017 03 15 SeJ init

### imports
import pantilthat

# pantilt settings
pan = 20
tilt = 0

# offsets
poff = 20
toff = 30


pantilthat.pan(pan + poff)
pantilthat.tilt(tilt + toff)

